version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: FakeItEasy
    versions:
    - 7.0.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
